name: CI
on:
  pull_request:
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
jobs:
  test:
    name: ${{ matrix.testMode }} Test on Unity ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2021.1.2f1
        testMode:
          - editmode
          - playmode
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Cache
        uses: actions/cache@v2.1.4
        with:
          path: Library
          key: Library-${{ hashFiles('**/packages-lock.json') }}
          restore-keys: |
            Library-
      - name: Unity - Test Runner
        id: tests
        uses: game-ci/unity-test-runner@v2
        with:
          unityVersion: ${{ matrix.unityVersion }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          artifactsPath: ${{ matrix.testMode }}-artifacts
          testMode: ${{ matrix.testMode }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ${{ steps.tests.outputs.artifactsPath }}